<div class="span12">
	<div id="form-header">
        <div class="half">	
        	<h1>Stellvertreter</h1>
            <p>Einleitungstext... Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.  </p>	
        </div>	
        <div class="control-bar">
        <!-- back button -->
       	<a class="btn btn-icon" href="<?php echo $this->backUrl; ?>"><img src="[CONFIG:url_client]assets/img/back.png"></a>         
        <!-- submit button -->
        <a class="btn btn-blue" onclick="$('form').submit();"><img src="[CONFIG:url_client]assets/img/submit.png">Submit</a>
        <?php if(is_array($this->errors)): ?>
            <div class="alert page-error"><b>Es gibt Fehler!</b></div>
        <?php endif; ?>
        </div>
        <div class="user-bar">
            <span class="user"><img src="[CONFIG:url_client]assets/img/login-user.png">&nbsp;&nbsp;<?php echo $this->sessionmail; ?></span>
            <a href="<?php echo $this->logoutUrl; ?>" class="logout"></a>
        </div>
    </div>
    <div class="clearfix"></div>
    <hr /> 
    <br />
</div>
<div class="span12">
<form id="form" action="<?php echo $this->actionUrl; ?>" method="post" class="form-horizontal">
    <?php if(is_array($this->errors)): ?>
    <div class="alert alert-error">Es gibt Fehler!</div>
    <?php endif; ?>
    
    <div class="control-group">
        <label class="control-label" for="stellvertreter_mail">E-Mail des Stellvertreters</label>
        <div class="controls">
            <div class="input-append">
                <input class="input-large" type="text" id="stellvertreter_mail" name="stellvertreter_mail" placeholder="a.name" value="<?php if($this->entity): echo $this->entity['stellvertreter_mail']; endif; ?>" />
                <span class="add-on"><?php echo $this->mailDomain; ?></span>
            </div>
            
            <?php if($this->errors['stellvertreter_mail']): ?>
            <div>
                <?php foreach($this->errors['stellvertreter_mail'] as $errorcode => $array): ?>
                <span class="label label-important">Fehler!</span> <?php echo $errorcode." (".$array['options']['errormsg'].")"; ?><br/>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>           
                
        </div>
    </div>
</form>
</div>
<div class="clearfix"></div>