<?php

    function showError($error)
    {
        if($error): ?>
        <div>
            <?php foreach($error as $errorcode => $array): ?>
            <span class="label label-important">Fehler!</span> <?php echo $errorcode." (".$array['options']['errormsg'].")"; ?><br/>
            <?php endforeach; ?>
        </div>
        <?php endif;
    }

?>

<h2>
    CSV Upload
</h2>
<div class="well well-small">
    <a href="<?php echo $this->backurl; ?>">zur&uuml;ck</a>
</div>
<div class="well well-small">
    Einleitungstext...
</div>
<form action="<?php echo $this->actionUrl; ?>" method="post" class="form-horizontal" enctype="multipart/form-data">
    <?php if(is_array($this->errors)): ?>
    <div class="alert alert-error">
        <p>Es gibt Fehler!</p>
        <ul>
            <?php foreach($this->errors as $row => $invalid): ?>
            <li>Zeile <?php echo $row; ?>: <?php print_r($invalid['errors']); ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
    
    <div class="control-group">
        <label id="csv_label" class="control-label" for="csv">CSV Datei</label>
        <div class="controls">
            <input class="input-medium" type="file" id="csv" name="csv" />
            <?php showError($this->errors['unternehmenshortcut']); ?>
        </div>
    </div>
    
    <button type="submit" class="btn">Submit</button>

</form>