<script type="text/javascript" language="javascript">
$(document).ready(function() {
        
    oTable = $('#teilnehmertabelle').dataTable({
        "bJQueryUI": true, 
        "sPaginationType": "full_numbers", 
        "aoColumns": [ null, null, null, null, null,null, { "bSortable": false } ],
        "bStateSave": true 
    });
    
    <?php if ($this->response == '1'): ?>
        var data = $('<div class="success message">Es wurde erfolgreich gespeichert</div>');
    <?php  elseif ($this->response == '2'): ?>
        var data = $('<div class="failure message">Die CSV Daten wurden erfolgreich hochgeladen</div>');
    <?php else: $skip=1; endif; ?>
    <?php if($skip != 1): ?>
    var popup= $('<div id="popup">');
    popup.append(data);
    $('body').append(popup);
    popup.css("position", "absolute");
    popup.css("top", ($(window).height() - popup.height()) / 2 + $(window).scrollTop() + "px");
    popup.css("left", ($(window).width() - popup.width()) / 2 + $(window).scrollLeft() + "px");
    popup.fadeOut(2000);
    <?php endif; ?>
});
</script>

<div class="span12">
	<div id="form-header">
        <div class="half">	
        	<h1>Teilnehmer</h1>
            <p>Einleitungstext... Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.  </p>	
        </div>	
        <div class="control-bar">
            <!-- back button -->
            <a class="btn btn-icon" href="<?php echo $this->backUrl; ?>"><img src="[CONFIG:url_client]assets/img/back.png"></a> 
            <!-- back button -->
            <a href="<?php echo $this->addUrl; ?>" class="btn btn-icon"><img src="[CONFIG:url_client]assets/img/add.png"></a>
            <!-- Upload button -->
            <a class="btn btn-icon" href="<?php echo $this->uploadUrl; ?>"><img src="[CONFIG:url_client]assets/img/upload.png"></a> 
            <!-- Download button -->
            <a class="btn btn-icon" href="<?php echo $this->downloadUrl; ?>"><img src="[CONFIG:url_client]assets/img/download.png"></a>  
            <!-- Tagungdetails button -->
            <a class="btn btn-icon" href="<?php echo $this->detailsUrl; ?>"><img src="[CONFIG:url_client]assets/img/tagung-details.png"></a> 
            <!-- Stellvertereter button -->
            <a class="btn btn-icon btn-adjusted" href="<?php echo $this->editReplacementUrl; ?>"><img src="[CONFIG:url_client]assets/img/stellvertreter.png"></a>
        </div>
        <div class="user-bar">
            <span class="user"><img src="[CONFIG:url_client]assets/img/login-user.png">&nbsp;&nbsp;<?php echo $this->sessionmail; ?></span>
            <a href="<?php echo $this->logoutUrl; ?>" class="logout"></a>
        </div>
    </div>
    <div class="clearfix"></div>
    <hr /> 
    <br />
</div>
<div class="span12">
    <table class="table" id="teilnehmertabelle">
        <thead>
            <tr>
                <th>&uuml;bertragen</th>
                <th>Referenznummer</th>
                <th>Name</th>
                <th>Unternehmen</th>
                <th>Zahl</th>
                <th>Betrag</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->entities as $entity): ?>
            <tr>
                <td><?php 
                    if ($entity->getValueByKey('teilnehmer_intern') == 1) {
                        echo "intern";
                    }
                    elseif($entity->getValueByKey('submitted')) {
                        echo $entity->getValueByKey('submitted'); 
                    }
                    else {
                        ?><input type="checkbox" /><?php
                    }
                ?></td>
                <td><?php echo $entity->getValueByKey('id')+400000; ?></td>
                <td><?php echo $entity->getValueByKey('nachname').' '.$entity->getValueByKey('vorname'); ?></td>
                <td><?php echo $entity->getValueByKey('unternehmen'); ?></td>
                <td><?php echo $entity->getValueByKey('zahlweise'); ?></td>
                <td><?php echo $entity->getValueByKey('betrag'); ?></td>
                <td><?php
                    if ($entity->getValueByKey('submitted')) {
                        ?><a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showParticipantDetails", "id"=>$entity->getValueByKey('id'), "eventId"=>$entity->getValueByKey('event_id'))); ?>">anzeigen</a><?php
                    }
                    else {
                        ?><a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showEditParticipantForm", "id"=>$entity->getValueByKey('id'), "eventId"=>$entity->getValueByKey('event_id'))); ?>">bearbeiten</a><?php
                    }
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="clearfix"></div>
