<h1>Teilnehmer</h1>
<div>
    <a href="<?php echo $this->backUrl; ?>">zur&uuml;ck</a> | 
    <a href="<?php echo $this->addUrl; ?>">Teilnehmer hinzuf&uuml;gen</a> | 
    <a href="<?php echo $this->uploadUrl; ?>">Teilnehmer CSV hochladen</a> | 
    <a href="<?php echo $this->downloadUrl; ?>">Teilnehmer CSV herunterladen</a> | 
    <a href="<?php echo $this->detailsUrl; ?>">Tagungsdetails</a> | 
    <a href="<?php echo $this->replacementUrl; ?>">Stellvertreter festlegen</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>&uuml;bertragen</th>
            <th>Referenznummer</th>
            <th>Name</th>
            <th>Unternehmen</th>
            <th>Zahl</th>
            <th>Betrag</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->entities as $entity): ?>
        <tr>
            <td><?php 
                if ($entity->getValueByKey('teilnehmer_intern') == 1) {
                    echo "intern";
                }
                elseif($entity->getValueByKey('submitted')) {
                    echo $entity->getValueByKey('submitted'); 
                }
                else {
                    ?><input type="checkbox" /><?php
                }
            ?></td>
            <td><?php echo $entity->getValueByKey('id')+400000; ?></td>
            <td><?php echo $entity->getValueByKey('nachname').' '.$entity->getValueByKey('vorname'); ?></td>
            <td><?php echo $entity->getValueByKey('unternehmen'); ?></td>
            <td><?php echo $entity->getValueByKey('zahlweise'); ?></td>
            <td><?php echo $entity->getValueByKey('betrag'); ?></td>
            <td><?php
                if ($entity->getValueByKey('submitted')) {
                    ?><a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showParticipantDetails", "id"=>$entity->getValueByKey('id'), "eventId"=>$entity->getValueByKey('event_id'))); ?>">anzeigen</a><?php
                }
                else {
                    ?><a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showEditParticipantForm", "id"=>$entity->getValueByKey('id'), "eventId"=>$entity->getValueByKey('event_id'))); ?>">bearbeiten</a><?php
                }
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>