<h2>
    Tagung
</h2>
<div class="well well-small">
    <a href="<?php echo $this->backurl; ?>">zur&uuml;ck</a> | <a href="<?php echo $this->editReplacementUrl; ?>">Stellvertreter festlegen</a>
</div>
<div class="well well-small">
    <dl>
        <dt>Buchungskreis</dt>
        <dd><?php echo $this->entity['buchungskreis']; ?></dd>

        <dt>Veranstaltungsschl&uuml;ssel</dt>
        <dd><?php echo $this->entity['v_schluessel']; ?></dd>

        <dt>Auftrags-/Projektnummer</dt>
        <dd><?php echo $this->entity['auftragsnr']; ?></dd>

        <dt>Bezeichnung</dt>
        <dd><?php echo $this->entity['bezeichnung']; ?></dd>

        <dt>Veranstaltungsland</dt>
        <dd><?php echo $this->entity['v_land']; ?></dd>

        <dt>Veranstaltungsort</dt>
        <dd><?php echo $this->entity['v_ort']; ?></dd>

        <dt>Beginn der Anmeldefrist</dt>
        <dd><?php echo $this->entity['anmeldefrist_beginn']; ?></dd>

        <dt>Ende der Anmeldefrist</dt>
        <dd><?php echo $this->entity['anmeldefrist_ende']; ?></dd>

        <dt>Beginn der Veranstaltung</dt>
        <dd><?php echo $this->entity['v_beginn']; ?></dd>

        <dt>Ende der Veranstaltung</dt>
        <dd><?php echo $this->entity['v_ende']; ?></dd>

        <dt>CPD Debitorkonto</dt>
        <dd><?php echo $this->entity['cpd_konto']; ?></dd>

        <dt>Erl&ouml;skonto</dt>
        <dd><?php echo $this->entity['erloeskonto']; ?></dd>

        <dt>Steuerkennzeichen</dt>
        <dd><?php echo $this->entity['steuerkennzeichen']; ?></dd>

        <dt>Steuersatz</dt>
        <dd><?php echo $this->entity['steuersatz']; ?></dd>

        <dt>Ansprechpartner im Institut</dt>
        <dd><?php echo $this->entity['ansprechpartner']; ?></dd>

        <dt>Telefon des AP</dt>
        <dd><?php echo $this->entity['ansprechpartner_tel']; ?></dd>

        <dt>Organisationseinheit des veranstaltenden Instituts</dt>
        <dd><?php echo $this->entity['organisationseinheit']; ?></dd>

        <dt>Email des AP</dt>
        <dd><?php echo $this->entity['ansprechpartner_mail']; ?></dd>

        <dt>Standardbetrag</dt>
        <dd><?php echo $this->entity['standardbetrag']; ?></dd>

        <dt>E-Mail des Stellvertreters</dt>
        <dd><?php echo $this->entity['stellvertreter_mail']; ?></dd>

    </dl>
</div>