<div class="span12">
	<div id="form-header">
        <div class="half">	
            <h1>Tagung</h1>
            <p>Einleitungstext... Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.  </p>	
        </div>      
        <div class="control-bar">
        <!-- back button -->
        <a class="btn btn-icon" id="back" href="<?php echo $this->backUrl; ?>"><img src="[CONFIG:url_client]assets/img/back.png"></a> 
        <a class="btn btn-icon btn-adjusted" href="<?php echo $this->editReplacementUrl; ?>"><img src="[CONFIG:url_client]assets/img/stellvertreter.png"></a> 
        <a class="btn btn-icon btn-adjusted" href="#"><img src="[CONFIG:url_client]assets/img/teilnehmer-liste.png"></a> 
        </div>   
        <div class="user-bar">
            <span class="user"><img src="[CONFIG:url_client]assets/img/login-user.png">&nbsp;&nbsp;<?php echo $this->sessionmail; ?></span>
            <a href="<?php echo $this->logoutUrl; ?>" class="logout"></a>
        </div>   
    </div>
    <div class="clearfix"></div>   
    <hr />
    <br />
</div>

<div class="span12">
    <dl class="dl-horizontal">
        <dt>Buchungskreis</dt>
        <dd><?php echo $this->entity['buchungskreis']; ?></dd>

        <dt>Veranstaltungsschl&uuml;ssel</dt>
        <dd><?php echo $this->entity['v_schluessel']; ?></dd>

        <dt>Auftrags-/Projektnummer</dt>
        <dd><?php echo $this->entity['auftragsnr']; ?></dd>

        <dt>Bezeichnung</dt>
        <dd><?php echo $this->entity['bezeichnung']; ?></dd>

        <dt>Veranstaltungsland</dt>
        <dd><?php echo $this->entity['v_land']; ?></dd>

        <dt>Veranstaltungsort</dt>
        <dd><?php echo $this->entity['v_ort']; ?></dd>

        <dt>Beginn der Anmeldefrist</dt>
        <dd><?php echo $this->entity['anmeldefrist_beginn']; ?></dd>

        <dt>Ende der Anmeldefrist</dt>
        <dd><?php echo $this->entity['anmeldefrist_ende']; ?></dd>

        <dt>Beginn der Veranstaltung</dt>
        <dd><?php echo $this->entity['v_beginn']; ?></dd>

        <dt>Ende der Veranstaltung</dt>
        <dd><?php echo $this->entity['v_ende']; ?></dd>

        <dt>CPD Debitorkonto</dt>
        <dd><?php echo $this->entity['cpd_konto']; ?></dd>

        <dt>Erl&ouml;skonto</dt>
        <dd><?php echo $this->entity['erloeskonto']; ?></dd>

        <dt>Steuerkennzeichen</dt>
        <dd><?php echo $this->entity['steuerkennzeichen']; ?></dd>

        <dt>Steuersatz</dt>
        <dd><?php echo $this->entity['steuersatz']; ?></dd>

        <dt>Ansprechpartner im Institut</dt>
        <dd><?php echo $this->entity['ansprechpartner']; ?></dd>

        <dt>Telefon des AP</dt>
        <dd><?php echo $this->entity['ansprechpartner_tel']; ?></dd>

        <dt>Organisationseinheit des veranstaltenden Instituts</dt>
        <dd><?php echo $this->entity['organisationseinheit']; ?></dd>

        <dt>Email des AP</dt>
        <dd><?php echo $this->entity['ansprechpartner_mail']; ?><?php echo $this->mailDomain; ?></dd>

        <dt>Standardbetrag</dt>
        <dd><?php echo $this->entity['standardbetrag']; ?></dd>

        <dt>E-Mail des Stellvertreters</dt>
        <dd><?php echo $this->entity['stellvertreter_mail']; ?><?php echo $this->mailDomain; ?></dd>

    </dl>
</div>
<div class="clearfix"></div>