<div class="span12">
	<div id="form-header">
        <div class="half">	
            <h1>Tagung</h1>
            <p>Einleitungstext... Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.  </p>	
        </div>      
        <div class="control-bar">
        <!-- back button -->
        <a class="btn btn-icon" id="back" href="<?php echo $this->backUrl; ?>"><img src="[CONFIG:url_client]assets/img/back.png"></a> 
        <a class="btn btn-icon btn-adjusted" href="<?php echo $this->editReplacementUrl; ?>"><img src="[CONFIG:url_client]assets/img/stellvertreter.png"></a> 
        <a class="btn btn-icon btn-adjusted" href="<?php echo $this->participantlistUrl; ?>"><img src="[CONFIG:url_client]assets/img/teilnehmer-liste.png"></a>
        </div>   
        <div class="user-bar">
            <span class="user"><img src="[CONFIG:url_client]assets/img/login-user.png">&nbsp;&nbsp;<?php echo $this->sessionmail; ?></span>
            <a href="<?php echo $this->logoutUrl; ?>" class="logout"></a>
        </div>   
    </div>
    <div class="clearfix"></div>   
    <hr />
    <br />
</div>
<div class="span12">
    <h2>Tagungsdetails</h2>
    <hr />
</div>
<div class="light-gray-block-table">
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>Buchungskreis:</strong></td>
                    <td><?php echo $this->entity['buchungskreis']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Auftrags-/Projektnummer:</strong></td>
                    <td><?php echo $this->entity['auftragsnr']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Veranstaltungsland:</strong></td>
                    <td><?php echo $this->entity['v_land']; ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>Veranstaltungsschl&uuml;ssel:</strong></td>
                    <td><?php echo $this->entity['v_schluessel']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Bezeichnung:</strong></td>
                    <td><?php echo $this->entity['bezeichnung']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Veranstaltungsort:</strong></td>
                    <td><?php echo $this->entity['v_ort']; ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    
</div>
<div class="span12">
    <h2>Tagungsdaten</h2>
    <hr />
</div>
<div class="light-gray-block-table">
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>Beginn der Anmeldefrist:</strong></td>
                    <td><?php echo $this->entity['anmeldefrist_beginn']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Beginn der Veranstaltung:</strong></td>
                    <td><?php echo $this->entity['v_beginn']; ?></td>
                </tr>
            </tbody>
        </table>           
    </div>
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>Ende der Anmeldefrist:</strong></td>
                    <td><?php echo $this->entity['anmeldefrist_ende']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Ende der Veranstaltung:</strong></td>
                    <td><?php echo $this->entity['v_ende']; ?></td>
                </tr>
            </tbody>
        </table>  
    </div>
</div>
<div class="span12">
    <h2>Finanzdaten</h2>
    <hr />
</div>
<div class="light-gray-block-table">
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>CPD Debitorkonto:</strong></td>
                    <td><?php echo $this->entity['cpd_konto']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Steuerkennzeichen:</strong></td>
                    <td><?php echo $this->entity['steuerkennzeichen']; ?></td>
                </tr>
            </tbody>
        </table>    
    </div>
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>Erl&ouml;skonto:</strong></td>
                    <td><?php echo $this->entity['erloeskonto']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Steuersatz:</strong></td>
                    <td><?php echo $this->entity['steuersatz']; ?></td>
                </tr>
            </tbody>
        </table>   
    </div>
</div>
<div class="span12">
    <h2>Ansprechpartner</h2>
    <hr />
</div>
<div class="light-gray-block-table">
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>Ansprechpartner im Institut:</strong></td>
                    <td><?php echo $this->entity['ansprechpartner']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Organisationseinheit des veranstaltenden Instituts:</strong></td>
                    <td><?php echo $this->entity['organisationseinheit']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Standardbetrag:</strong></td>
                    <td><?php echo $this->entity['standardbetrag']; ?></td>
                </tr>
            </tbody>
        </table>       
    </div>
    <div class="half left">
        <table width="100%">
            <tbody>
                <tr>
                    <td class="table-cell"><strong>Telefon des AP:</strong></td>
                    <td><?php echo $this->entity['ansprechpartner_tel']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>Email des AP:</strong></td>
                    <td><?php echo $this->entity['ansprechpartner_mail']; ?></td>
                </tr>
                <tr>
                    <td class="table-cell"><strong>E-Mail des Stellvertreters:</strong></td>
                    <td><?php echo $this->entity['stellvertreter_mail']; ?></td>
                </tr>
            </tbody>
        </table>      
    </div>
</div>        
<div class="clearfix"></div>