<h1>Tagungen</h1>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Typ</th>
            <th>Tagung</th>
            <th>Anmeldezeitraum</th>
            <th>Funktionen</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->entities as $entity): ?>
        <tr>
            <td><?php echo $entity->getValueByKey('id'); ?></td>
            <td>eigene</td>
            <td><a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showEventDetails", "id"=>$entity->getValueByKey('id'))); ?>"><?php echo $entity->getValueByKey('bezeichnung'); ?></a></td>
            <td><?php echo $this->formatDate($entity->getValueByKey('v_beginn')); ?> - <?php echo $this->formatDate($entity->getValueByKey('v_ende')); ?></td>
            <td><a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showParticipantList", "id"=>$entity->getValueByKey('id'))); ?>">Teilnehmer verwalten</a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>