<div class="span12">
	<div id="form-header">
        <div class="half">	
            <h1>Entities</h1>
            <p>Einleitungstext... Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.  </p>	
        </div>      
        <div class="control-bar">
            <a href="<?php echo $this->addUrl; ?>" class="btn btn-icon">
            <img src="[CONFIG:url_client]assets/img/add.png"></a>	
        </div>      
    </div>
    <div class="clearfix"></div>   
    <hr />
    <br />
</div>
<div class="span12">
    <?php if($this->entities): ?>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tagung</th>
                <th>Anmeldezeitraum</th>
                <th>Tagungsschl&uuml;ssel</th>
                <th>Kontierungsobjekt</th>
            </tr>
        </thead>
        <tbody>
        	
            <?php foreach ($this->entities as $entity): ?>
            <tr>
                <td><?php echo $entity->getValueByKey('id'); ?></td>
                <td id="tagung_name"><a class="icon_edit" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showEditForm", "id"=>$entity->getValueByKey('id'))); ?>"><?php echo $entity->getValueByKey('bezeichnung'); ?></a></td>
                <td><?php echo $this->formatDate($entity->getValueByKey('anmeldefrist_beginn')); ?> - <?php echo $this->formatDate($entity->getValueByKey('anmeldefrist_ende')); ?></td>
                <td><?php echo $entity->getValueByKey('v_schluessel'); ?></td>
                <td><?php echo $entity->getValueByKey('cpd_konto'); ?></td>
            </tr>
        	<?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
    <div class="alert">
	     <p><strong>Achtung!</strong> Keine Daten vorhanden.</p>
    </div>
    <?php endif; ?>
</div>
<div class="clearfix"></div>