
<div class="span12">
	<div id="form-header">
    	<div class="half">
		    <h1>Tagungen</h1>
            <p>Einleitungstext... Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.  </p>	
        </div>
        <div class="user-bar">
            <span class="user"><img src="[CONFIG:url_client]assets/img/login-user.png">&nbsp;&nbsp;<?php echo $this->sessionmail; ?></span>
            <a href="<?php echo $this->logoutUrl; ?>" class="logout"></a>
        </div>
    </div>
    <div class="clearfix"></div>   
    <hr />
    <br />
</div>
<div class="span12">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Typ</th>
                <th>Tagung</th>
                <th>Anmeldezeitraum</th>
                <th>Funktionen</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->entities as $entity): ?>
            <tr>
                <td><?php echo $entity->getValueByKey('id'); ?></td>
                <td><?php 
                if ($entity->getValueByKey('ansprechpartner_mail') == $this->sessionmail):
                ?>eigene<?php    
                else:
                ?>in Vertretung<?php    
                endif;
                ?></td>
                <td id="tagung_name"><a class="icon_edit" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showEventDetails", "id"=>$entity->getValueByKey('id'))); ?>"><?php echo $entity->getValueByKey('bezeichnung'); ?></a></td>
                <td><?php echo $this->formatDate($entity->getValueByKey('anmeldefrist_beginn')); ?> - <?php echo $this->formatDate($entity->getValueByKey('anmeldefrist_ende')); ?></td>
                <td><a class="icon_edit" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showParticipantList", "eventId"=>$entity->getValueByKey('id'))); ?>">Teilnehmer verwalten</a></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="clearfix"></div>