<h1>Entities</h1>
<div>
    <a href="<?php echo $this->addUrl; ?>">add entity</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Tagung</th>
            <th>Anmeldezeitraum</th>
            <th>Tagungsschl&uuml;ssel</th>
            <th>Kontierungsobjekt</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->entities as $entity): ?>
        <tr>
            <td><?php echo $entity->getValueByKey('id'); ?></td>
            <td><a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showEditForm", "id"=>$entity->getValueByKey('id'))); ?>"><?php echo $entity->getValueByKey('bezeichnung'); ?></a></td>
            <td><?php echo $this->formatDate($entity->getValueByKey('v_beginn')); ?> - <?php echo $this->formatDate($entity->getValueByKey('v_ende')); ?></td>
            <td><?php echo $entity->getValueByKey('v_schluessel'); ?></td>
            <td><?php echo $entity->getValueByKey('cpd_konto'); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>