<h2>
    Stellvertreter
</h2>
<div class="well well-small">
    <a href="<?php echo $this->backurl; ?>">zur&uuml;ck</a>
</div>
<div class="well well-small">
    Einleitungstext...
</div>
<form action="<?php echo $this->actionUrl; ?>" method="post" class="form-horizontal">
    <?php if(is_array($this->errors)): ?>
    <div class="alert alert-error">Es gibt Fehler!</div>
    <?php endif; ?>
    
    <div class="control-group">
        <label class="control-label" for="stellvertreter_mail">E-Mail des Stellvertreters</label>
        <div class="controls">
            <div class="input-append">
                <input class="input-large" type="text" id="stellvertreter_mail" name="stellvertreter_mail" placeholder="a.name" value="<?php if($this->entity): echo $this->entity['stellvertreter_mail']; endif; ?>" />
                <span class="add-on"><?php echo $this->mailDomain; ?></span>
            </div>
            
            <?php if($this->errors['stellvertreter_mail']): ?>
            <div>
                <?php foreach($this->errors['stellvertreter_mail'] as $errorcode => $array): ?>
                <span class="label label-important">Fehler!</span> <?php echo $errorcode." (".$array['options']['errormsg'].")"; ?><br/>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>           
                
        </div>
    </div>

    <button type="submit" class="btn">Submit</button>

</form>